// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/checkCompliance": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Send request for compliance check",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "compliance"
                ],
                "summary": "Send request for compliance check",
                "parameters": [
                    {
                        "description": "object to update",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ComplianceCheckRequestDto"
                        }
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/service.ErrorOutput"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/service.ErrorOutput"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.Address": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "full_address": {
                    "type": "string"
                },
                "isoCountryCode": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "dto.ComplianceCheckRequestDto": {
            "type": "object",
            "properties": {
                "checkRules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ComplianceCheckRule"
                    }
                },
                "complianceEntity": {
                    "$ref": "#/definitions/dto.ComplianceEntity"
                },
                "complianceProvider": {
                    "$ref": "#/definitions/enum.KYCProviderType"
                },
                "pwgEntityGuid": {
                    "type": "string"
                },
                "pwgEntityType": {
                    "$ref": "#/definitions/enum.PwgEntityType"
                }
            }
        },
        "dto.ComplianceCheckRule": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "details": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                }
            }
        },
        "dto.ComplianceEntity": {
            "type": "object",
            "properties": {
                "individualPerson": {
                    "$ref": "#/definitions/dto.IndividualPerson"
                },
                "institution": {
                    "$ref": "#/definitions/dto.Institution"
                }
            }
        },
        "dto.IndividualPerson": {
            "type": "object",
            "properties": {
                "address": {
                    "$ref": "#/definitions/dto.Address"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "userPwgGuid": {
                    "type": "string"
                }
            }
        },
        "dto.Institution": {
            "type": "object",
            "properties": {
                "companyAddress": {
                    "$ref": "#/definitions/dto.Address"
                },
                "controlPersons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.IndividualPerson"
                    }
                },
                "institutionPwgGuid": {
                    "type": "string"
                },
                "legalName": {
                    "type": "string"
                }
            }
        },
        "enum.KYCProviderType": {
            "type": "string",
            "enum": [
                "finclusive",
                "pwgMock"
            ],
            "x-enum-varnames": [
                "KYCProviderFinclusive",
                "KYCProviderPwgMock"
            ]
        },
        "enum.PwgEntityType": {
            "type": "string",
            "enum": [
                "usersAccount",
                "institution"
            ],
            "x-enum-varnames": [
                "PwgEntityUsersAccount",
                "PwgEntityInstitution"
            ]
        },
        "service.ErrorOutput": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
